name: fixifypartner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.4

  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_maps_flutter: ^2.12.0
  flutter_local_notifications: ^19.0.0

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  get: ^4.6.5

  firebase_core: ^3.12.1
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/imagefixify.png
    - assets/images/6902611.png
    - assets/images/themecomingsoon.jpg
    - assets/images/service_booking.png
    - assets/images/profile image.png
    - assets/images/local_help.png
    - assets/images/experienced_help.png
    - assets/icons/carpentry.png
    - assets/icons/electrical.png
    - assets/icons/home_installation.png
    - assets/icons/painting.png
    - assets/icons/plumbing.png