// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe4LAkRHFzSLyuLuC6zPUdd-4WmFg54Eo',
    appId: '1:608337521706:web:56716826913fefd252a753',
    messagingSenderId: '608337521706',
    projectId: 'fixify-21ef4',
    authDomain: 'fixify-21ef4.firebaseapp.com',
    storageBucket: 'fixify-21ef4.firebasestorage.app',
    measurementId: 'G-YLVRW6EEJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYA8aYWt78jEgutB59LixylS_bGyyfTgU',
    appId: '1:608337521706:android:4199c0f757c6fb7a52a753',
    messagingSenderId: '608337521706',
    projectId: 'fixify-21ef4',
    storageBucket: 'fixify-21ef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8IwOqtMgnAmkBKCz1NP_-TaKg8Uw85_4',
    appId: '1:608337521706:ios:7eaed64b7d28103252a753',
    messagingSenderId: '608337521706',
    projectId: 'fixify-21ef4',
    storageBucket: 'fixify-21ef4.firebasestorage.app',
    androidClientId: '608337521706-d68lfuftosjc8bn7m06sbk14muveia20.apps.googleusercontent.com',
    iosClientId: '608337521706-bblaaga1esr8s8e32s98m98u0galv7sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixifypartner',
  );

}